export const RECEIVE_AUTH_DATA = 'RECEIVE_AUTH_DATA';
export const USER_LOGOUT = 'USER_LOGOUT';
export const PROJECT_IS_CREATED = 'PROJECT_IS_CREATED';
export const PROJECTS_LIST_RECEIVED = 'PROJECTS_LIST_RECEIVED';
