export const PROJECT_IS_CREATED = 'PROJECT_IS_CREATED';
export const PROJECTS_LIST_RECEIVED = 'PROJECTS_LIST_RECEIVED';
export const PROJECTS_IS_DELETED = 'PROJECTS_IS_DELETED';
export const PROJECTS_IS_EDITED = 'PROJECTS_IS_EDITED';
